### ISSUE TITLE
Error withdraw and re-register new key

### ISSUE THREAD

**Issue by goto5k** [solana-labs/stake-o-matic#109]
I register testnet and mainnet key the same. Now I can't withdraw and re-register new key for mainnet (Error: "Registration already exists")
When I try withdraw registration
`[2021-06-17T12:40:41.908291066Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction
[2021-06-17T12:40:41.908303953Z DEBUG solana_client::rpc_client]   1: Program reg8X1V65CSdmrtEjMgnXZk96b9SUSQrJ8n1rP1ZMg7 invoke [1]
[2021-06-17T12:40:41.908305990Z DEBUG solana_client::rpc_client]   2: Program log: Withdraw
[2021-06-17T12:40:41.908307218Z DEBUG solana_client::rpc_client]   3: Program log: Error: mainnet and testnet identities must be unique
[2021-06-17T12:40:41.908308479Z DEBUG solana_client::rpc_client]   4: Program reg8X1V65CSdmrtEjMgnXZk96b9SUSQrJ8n1rP1ZMg7 consumed 2160 of 200000 compute units
[2021-06-17T12:40:41.908309831Z DEBUG solana_client::rpc_client]   5: Program reg8X1V65CSdmrtEjMgnXZk96b9SUSQrJ8n1rP1ZMg7 failed: invalid account data for instruction
[2021-06-17T12:40:41.908311228Z DEBUG solana_client::rpc_client]
Error: "error: send transaction: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction [5 log messages]"
`

**Comment by mvines** [comment]
Fixed

**Comment by calypso-it** [comment]
Issue still present on `v1.0.5`:
`Error: "error: send transaction: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction [5 log messages]"`

**Comment by unordered-set** [comment]
> @mvines Issue still present on `v1.0.5`:
> `Error: "error: send transaction: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction [5 log messages]"`

It looks like the issue is in the on-chain program: https://discordapp.com/channels/428295358100013066/670512312339398668/875183788643192892
